import json
import os
from typing import Dict, Any, Optional

try:
    from strategies import STRATEGIES
except ImportError:
    STRATEGIES = {}

class StrategyExporter:
    """
    Exportador Cuantitativo Multiformato de Estrategias.
    Soporta exportación a:
    1. JSON Schema (para REST API, Web UI, bots de producción)
    2. Python Standalone Script (ejecutable autónomo 100% independiente del framework)
    3. TradingView PineScript v5 (para visualización, alertas y backtesting en TradingView)
    """

    @staticmethod
    def export_to_json(strategy_key: str, params: dict, symbol: str = "BTCUSDT", expiry: int = 1) -> str:
        strat_key = strategy_key.lower()
        strat_cls = STRATEGIES.get(strat_key)
        name = getattr(strat_cls, 'name', strategy_key.upper()) if strat_cls else strategy_key.upper()
        description = getattr(strat_cls, 'description', '') if strat_cls else ''
        
        schema = []
        if strat_cls and hasattr(strat_cls, 'get_params_schema'):
            try:
                schema = strat_cls().get_params_schema()
            except Exception:
                schema = []

        payload = {
            "strategy_key": strategy_key,
            "name": name,
            "description": description,
            "symbol": symbol,
            "expiry_candles": expiry,
            "parameters": params,
            "schema": schema,
            "version": "1.0.0",
            "metadata": {
                "created_by": "Antigravity Quant Engine",
                "target_winrate": ">80%",
                "engine_version": "2.5.0",
                "export_format": "JSON_REST_SCHEMA_V1"
            }
        }
        return json.dumps(payload, indent=2)

    @staticmethod
    def export_to_python(strategy_key: str, params: dict) -> str:
        """Genera un script ejecutable en Python puro independiente sin dependencias del framework."""
        strat_key = strategy_key.lower()
        p_repr = json.dumps(params, indent=4)

        if strat_key == "deesr":
            return f'''# Autogenerated Standalone Python Strategy Script: DEESR
# Strategy: Dual Extreme Envelope Stretch Reversal
# Created by Antigravity Quant Engine

import pandas as pd
import numpy as np

def compute_wilders_rsi(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    rsi_vals = np.full(n, np.nan, dtype=float)
    if n <= period:
        return pd.Series(rsi_vals, index=close.index)
    gains = np.zeros(n)
    losses = np.zeros(n)
    for i in range(1, n):
        diff = closes_val[i] - closes_val[i - 1]
        if diff > 0:
            gains[i] = diff
        else:
            losses[i] = -diff
    avg_gain = np.sum(gains[1:period + 1]) / period
    avg_loss = np.sum(losses[1:period + 1]) / period
    if avg_loss == 0.0:
        rsi_vals[period] = 50.0 if avg_gain == 0.0 else 100.0
    else:
        rs = avg_gain / avg_loss
        rsi_vals[period] = 100.0 - (100.0 / (1.0 + rs))
    for i in range(period + 1, n):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        if avg_loss == 0.0:
            rsi_vals[i] = 50.0 if avg_gain == 0.0 else 100.0
        else:
            rs = avg_gain / avg_loss
            rsi_vals[i] = 100.0 - (100.0 / (1.0 + rs))
    return pd.Series(rsi_vals, index=close.index)

def compute_ema(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    ema_vals = np.full(n, np.nan, dtype=float)
    if n < period:
        return pd.Series(ema_vals, index=close.index)
    k = 2.0 / (period + 1)
    sma = np.sum(closes_val[:period]) / period
    ema_vals[period - 1] = sma
    for i in range(period, n):
        ema_vals[i] = closes_val[i] * k + ema_vals[i - 1] * (1.0 - k)
    return pd.Series(ema_vals, index=close.index)

def generate_signals(df: pd.DataFrame, params: dict = None) -> pd.Series:
    if params is None:
        params = {p_repr}
    p = params
    bb_period = int(p.get("bb_period", 20))
    bb_std_val = float(p.get("bb_std", 2.5))
    kc_period = int(p.get("kc_period", 20))
    kc_mult = float(p.get("kc_mult", 2.0))
    rsi_fast_p = int(p.get("rsi_fast_period", 3))
    rsi_slow_p = int(p.get("rsi_slow_period", 14))
    max_body = float(p.get("max_body_ratio", 0.45))
    min_wick = float(p.get("min_wick_ratio", 0.35))

    close = df['close']
    high = df['high']
    low = df['low']
    open_p = df['open']

    bb_sma = close.rolling(window=bb_period).mean()
    bb_sigma = close.rolling(window=bb_period).std(ddof=0)
    bb_lower = bb_sma - (bb_std_val * bb_sigma)
    bb_upper = bb_sma + (bb_std_val * bb_sigma)

    kc_ema = compute_ema(close, kc_period)
    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    atr = tr.rolling(window=kc_period).mean()
    kc_lower = kc_ema - (kc_mult * atr)
    kc_upper = kc_ema + (kc_mult * atr)

    rsi_fast = compute_wilders_rsi(close, rsi_fast_p)
    rsi_slow = compute_wilders_rsi(close, rsi_slow_p)

    candle_range = high - low
    body = (close - open_p).abs()
    lower_wick = np.minimum(open_p, close) - low
    upper_wick = high - np.maximum(open_p, close)

    valid_range = candle_range > 0
    body_ratio = pd.Series(np.where(valid_range, body / candle_range, 1.0), index=df.index)
    lower_wick_ratio = pd.Series(np.where(valid_range, lower_wick / candle_range, 0.0), index=df.index)
    upper_wick_ratio = pd.Series(np.where(valid_range, upper_wick / candle_range, 0.0), index=df.index)

    call_cond = (close <= bb_lower) & (low <= kc_lower) & (rsi_fast <= 15.0) & (rsi_slow <= 35.0) & (body_ratio <= max_body) & (lower_wick_ratio >= min_wick)
    put_cond = (close >= bb_upper) & (high >= kc_upper) & (rsi_fast >= 85.0) & (rsi_slow >= 65.0) & (body_ratio <= max_body) & (upper_wick_ratio >= min_wick)

    call_cond = call_cond & (~call_cond.shift(1).fillna(False))
    put_cond = put_cond & (~put_cond.shift(1).fillna(False))

    conflict = call_cond & put_cond
    call_cond = call_cond & (~conflict)
    put_cond = put_cond & (~conflict)

    signals = pd.Series(index=df.index, dtype=object)
    signals.loc[call_cond] = "CALL"
    signals.loc[put_cond] = "PUT"
    return signals

if __name__ == '__main__':
    print("Standalone Python Strategy 'DEESR' initialized.")
'''

        elif strat_key in ["islg", "islg_rs"]:
            return f'''# Autogenerated Standalone Python Strategy Script: ISLG_RS
# Strategy: Institutional Swing Liquidity Grab Sweep
# Created by Antigravity Quant Engine

import pandas as pd
import numpy as np

def compute_wilders_rsi(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    rsi_vals = np.full(n, np.nan, dtype=float)
    if n <= period:
        return pd.Series(rsi_vals, index=close.index)
    gains = np.zeros(n)
    losses = np.zeros(n)
    for i in range(1, n):
        diff = closes_val[i] - closes_val[i - 1]
        if diff > 0:
            gains[i] = diff
        else:
            losses[i] = -diff
    avg_gain = np.sum(gains[1:period + 1]) / period
    avg_loss = np.sum(losses[1:period + 1]) / period
    if avg_loss == 0.0:
        rsi_vals[period] = 50.0 if avg_gain == 0.0 else 100.0
    else:
        rs = avg_gain / avg_loss
        rsi_vals[period] = 100.0 - (100.0 / (1.0 + rs))
    for i in range(period + 1, n):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        if avg_loss == 0.0:
            rsi_vals[i] = 50.0 if avg_gain == 0.0 else 100.0
        else:
            rs = avg_gain / avg_loss
            rsi_vals[i] = 100.0 - (100.0 / (1.0 + rs))
    return pd.Series(rsi_vals, index=close.index)

def generate_signals(df: pd.DataFrame, params: dict = None) -> pd.Series:
    if params is None:
        params = {p_repr}
    p = params
    lookback = int(p.get("lookback_period", 50))
    sweep_ratio = float(p.get("min_sweep_atr_ratio", 0.15))
    wick_ratio = float(p.get("wick_ratio", 0.35))
    vol_mult = float(p.get("vol_mult", 1.3))
    rsi_period = int(p.get("rsi_period", 7))

    close = df['close']
    high = df['high']
    low = df['low']
    open_p = df['open']
    volume = df['volume'] if 'volume' in df.columns else pd.Series(0, index=df.index)

    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    atr = tr.rolling(window=14).mean()

    swing_high = high.shift(1).rolling(window=lookback).max()
    swing_low = low.shift(1).rolling(window=lookback).min()

    candle_range = high - low
    lower_wick = np.minimum(open_p, close) - low
    upper_wick = high - np.maximum(open_p, close)

    valid_range = candle_range > 0
    lower_wick_ratio = np.where(valid_range, lower_wick / candle_range, 0.0)
    upper_wick_ratio = np.where(valid_range, upper_wick / candle_range, 0.0)

    rsi = compute_wilders_rsi(close, rsi_period)

    has_vol = ('volume' in df.columns) and (df['volume'].fillna(0).sum() > 0)
    if has_vol:
        vol_sma = volume.rolling(window=20).mean()
        vol_spike = (vol_sma == 0) | (volume >= (vol_sma * vol_mult))
    else:
        vol_spike = pd.Series(True, index=df.index)

    put_sweep = (high > swing_high) & ((high - swing_high) >= (sweep_ratio * atr)) & (close <= (swing_high + 0.05 * atr)) & (upper_wick_ratio >= wick_ratio) & vol_spike & (rsi >= 70.0)
    call_sweep = (low < swing_low) & ((swing_low - low) >= (sweep_ratio * atr)) & (close >= (swing_low - 0.05 * atr)) & (lower_wick_ratio >= wick_ratio) & vol_spike & (rsi <= 30.0)

    call_sweep = call_sweep & (~call_sweep.shift(1).fillna(False))
    put_sweep = put_sweep & (~put_sweep.shift(1).fillna(False))

    conflict = call_sweep & put_sweep
    call_sweep = call_sweep & (~conflict)
    put_sweep = put_sweep & (~conflict)

    signals = pd.Series(index=df.index, dtype=object)
    signals.loc[call_sweep] = "CALL"
    signals.loc[put_sweep] = "PUT"
    return signals

if __name__ == '__main__':
    print("Standalone Python Strategy 'ISLG_RS' initialized.")
'''

        elif strat_key == "genetic_composite":
            return f'''# Autogenerated Standalone Python Strategy Script: GeneticComposite
# Strategy: Estrategia Genetica Combinada
# Created by Antigravity Quant Engine

import pandas as pd
import numpy as np

def compute_wilders_rsi(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    rsi_vals = np.full(n, np.nan, dtype=float)
    if n <= period:
        return pd.Series(rsi_vals, index=close.index)
    gains = np.zeros(n)
    losses = np.zeros(n)
    for i in range(1, n):
        diff = closes_val[i] - closes_val[i - 1]
        if diff > 0:
            gains[i] = diff
        else:
            losses[i] = -diff
    avg_gain = np.sum(gains[1:period + 1]) / period
    avg_loss = np.sum(losses[1:period + 1]) / period
    if avg_loss == 0.0:
        rsi_vals[period] = 50.0 if avg_gain == 0.0 else 100.0
    else:
        rs = avg_gain / avg_loss
        rsi_vals[period] = 100.0 - (100.0 / (1.0 + rs))
    for i in range(period + 1, n):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        if avg_loss == 0.0:
            rsi_vals[i] = 50.0 if avg_gain == 0.0 else 100.0
        else:
            rs = avg_gain / avg_loss
            rsi_vals[i] = 100.0 - (100.0 / (1.0 + rs))
    return pd.Series(rsi_vals, index=close.index)

def compute_ema(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    ema_vals = np.full(n, np.nan, dtype=float)
    if n < period:
        return pd.Series(ema_vals, index=close.index)
    k = 2.0 / (period + 1)
    sma = np.sum(closes_val[:period]) / period
    ema_vals[period - 1] = sma
    for i in range(period, n):
        ema_vals[i] = closes_val[i] * k + ema_vals[i - 1] * (1.0 - k)
    return pd.Series(ema_vals, index=close.index)

def generate_signals(df: pd.DataFrame, params: dict = None) -> pd.Series:
    if params is None:
        params = {p_repr}
    p = params
    rsi_period = int(p.get("rsi_period", 14))
    rsi_oversold = float(p.get("rsi_oversold", 30.0))
    rsi_overbought = float(p.get("rsi_overbought", 70.0))
    rsi_enabled = bool(p.get("rsi_enabled", True))

    bb_period = int(p.get("bb_period", 20))
    bb_std = float(p.get("bb_std", 2.0))
    bb_enabled = bool(p.get("bb_enabled", True))

    ema_fast_period = int(p.get("ema_fast_period", 9))
    ema_slow_period = int(p.get("ema_slow_period", 21))
    ema_enabled = bool(p.get("ema_enabled", False))

    htf_ema_period = int(p.get("htf_ema_period", 100))
    htf_ema_enabled = bool(p.get("htf_ema_enabled", False))

    close = df['close']
    open_p = df['open']
    high = df['high']
    low = df['low']
    orig_indices = df.index

    call_cond = pd.Series(True, index=orig_indices)
    put_cond = pd.Series(True, index=orig_indices)

    if rsi_enabled:
        rsi = compute_wilders_rsi(close, rsi_period)
        prev_rsi = rsi.shift(1)
        if not bb_enabled and not ema_enabled:
            rsi_call = (prev_rsi <= rsi_oversold) & (rsi > prev_rsi)
            rsi_put = (prev_rsi >= rsi_overbought) & (rsi < prev_rsi)
        else:
            rsi_call = rsi <= rsi_oversold
            rsi_put = rsi >= rsi_overbought
        call_cond = call_cond & rsi_call
        put_cond = put_cond & rsi_put

    if bb_enabled:
        sma = close.rolling(window=bb_period).mean()
        std = close.rolling(window=bb_period).std(ddof=0)
        upper_band = sma + (std * bb_std)
        lower_band = sma - (std * bb_std)

        prev_close = close.shift(1)
        prev_lower = lower_band.shift(1)
        prev_upper = upper_band.shift(1)

        if bool(p.get("volatility_filter_enabled", False)) and not rsi_enabled:
            bb_call = (close > upper_band) & (prev_close <= prev_upper)
            bb_put = (close < lower_band) & (prev_close >= prev_lower)
        else:
            bb_call = (prev_close >= prev_lower) & (close < lower_band)
            bb_put = (prev_close <= prev_upper) & (close > upper_band)
        call_cond = call_cond & bb_call
        put_cond = put_cond & bb_put

    if ema_enabled:
        ema_f = compute_ema(close, ema_fast_period)
        ema_s = compute_ema(close, ema_slow_period)
        prev_f = ema_f.shift(1)
        prev_s = ema_s.shift(1)

        if rsi_enabled:
            ema_call = (ema_f > ema_s) & (rsi <= rsi_oversold)
            ema_put = (ema_f < ema_s) & (rsi >= rsi_overbought)
        else:
            ema_call = (prev_f <= prev_s) & (ema_f > ema_s)
            ema_put = (prev_f >= prev_s) & (ema_f < ema_s)
        call_cond = call_cond & ema_call
        put_cond = put_cond & ema_put

    if bool(p.get("rejection_filter_enabled", False)):
        candle_range = high - low
        upper_wick = high - np.maximum(open_p, close)
        lower_wick = np.minimum(open_p, close) - low
        wick_ratio = float(p.get("pinbar_wick_ratio", 0.35))
        pin_bull = (candle_range > 0) & ((lower_wick / candle_range) >= wick_ratio)
        pin_bear = (candle_range > 0) & ((upper_wick / candle_range) >= wick_ratio)
        call_cond = call_cond & pin_bull
        put_cond = put_cond & pin_bear

    if bool(p.get("volatility_filter_enabled", False)) and bb_enabled:
        sma = close.rolling(window=bb_period).mean()
        std = close.rolling(window=bb_period).std(ddof=0)
        upper_band = sma + (std * bb_std)
        lower_band = sma - (std * bb_std)
        bb_width = (upper_band - lower_band) / close
        threshold = float(p.get("min_bb_width", 0.0))
        if threshold > 0.0:
            squeeze_active = bb_width <= threshold
        else:
            rolling_q30 = bb_width.rolling(window=100, min_periods=20).quantile(0.30)
            squeeze_active = bb_width <= rolling_q30.fillna(bb_width.quantile(0.30))
        if bb_enabled and rsi_enabled:
            sqz_call = ~squeeze_active
            sqz_put = ~squeeze_active
        else:
            prev_sqz = squeeze_active.shift(1).fillna(False)
            sqz_call = prev_sqz & (close > open_p)
            sqz_put = prev_sqz & (close < open_p)
        call_cond = call_cond & sqz_call
        put_cond = put_cond & sqz_put

    if htf_ema_enabled:
        htf_ema = compute_ema(close, htf_ema_period)
        call_cond = call_cond & (close > htf_ema)
        put_cond = put_cond & (close < htf_ema)

    call_cond = call_cond & (~call_cond.shift(1).fillna(False))
    put_cond = put_cond & (~put_cond.shift(1).fillna(False))

    conflict = call_cond & put_cond
    call_cond = call_cond & (~conflict)
    put_cond = put_cond & (~conflict)

    signals = pd.Series(index=orig_indices, dtype=object)
    if not rsi_enabled and not bb_enabled and not ema_enabled and not p.get("rejection_filter_enabled") and not p.get("volatility_filter_enabled") and not htf_ema_enabled:
        return signals

    signals.loc[call_cond] = "CALL"
    signals.loc[put_cond] = "PUT"
    return signals

if __name__ == '__main__':
    print("Standalone Python Strategy 'GeneticComposite' initialized.")
'''

        elif strat_key == "daily_confluence":
            return f'''# Autogenerated Standalone Python Strategy Script: DailyConfluence
# Strategy: Confluencia Diaria Multi-Activo
# Created by Antigravity Quant Engine

import pandas as pd
import numpy as np

def compute_wilders_rsi(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    rsi_vals = np.full(n, np.nan, dtype=float)
    if n <= period:
        return pd.Series(rsi_vals, index=close.index)
    gains = np.zeros(n)
    losses = np.zeros(n)
    for i in range(1, n):
        diff = closes_val[i] - closes_val[i - 1]
        if diff > 0:
            gains[i] = diff
        else:
            losses[i] = -diff
    avg_gain = np.sum(gains[1:period + 1]) / period
    avg_loss = np.sum(losses[1:period + 1]) / period
    if avg_loss == 0.0:
        rsi_vals[period] = 50.0 if avg_gain == 0.0 else 100.0
    else:
        rs = avg_gain / avg_loss
        rsi_vals[period] = 100.0 - (100.0 / (1.0 + rs))
    for i in range(period + 1, n):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        if avg_loss == 0.0:
            rsi_vals[i] = 50.0 if avg_gain == 0.0 else 100.0
        else:
            rs = avg_gain / avg_loss
            rsi_vals[i] = 100.0 - (100.0 / (1.0 + rs))
    return pd.Series(rsi_vals, index=close.index)

def compute_ema(close: pd.Series, period: int) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    ema_vals = np.full(n, np.nan, dtype=float)
    if n < period:
        return pd.Series(ema_vals, index=close.index)
    k = 2.0 / (period + 1)
    sma = np.sum(closes_val[:period]) / period
    ema_vals[period - 1] = sma
    for i in range(period, n):
        ema_vals[i] = closes_val[i] * k + ema_vals[i - 1] * (1.0 - k)
    return pd.Series(ema_vals, index=close.index)

def _resample_to_weekly(df_daily: pd.DataFrame) -> pd.DataFrame:
    df = df_daily.copy()
    if 'open_time' not in df.columns:
        return pd.DataFrame()
    if df['open_time'].max() > 2**32:
        df['datetime'] = pd.to_datetime(df['open_time'], unit='ms')
    else:
        df['datetime'] = pd.to_datetime(df['open_time'], unit='s')
    df.set_index('datetime', inplace=True)
    agg_dict = {{
        'open_time': 'first',
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last'
    }}
    if 'volume' in df.columns:
        agg_dict['volume'] = 'sum'
    df_weekly = df.resample('W-MON').agg(agg_dict)
    df_weekly.dropna(subset=['close'], inplace=True)
    df_weekly.reset_index(inplace=True)
    return df_weekly

def generate_signals(df: pd.DataFrame, params: dict = None) -> pd.Series:
    if params is None:
        params = {p_repr}
    p = params
    ema_weekly_p = int(p.get("ema_weekly_period", 20))
    ema_daily_p = int(p.get("ema_daily_period", 20))
    rsi_p = int(p.get("rsi_period", 14))
    pullback_tol = float(p.get("pullback_tolerance", 0.008))
    rsi_min_call = float(p.get("rsi_min_call", 25.0))
    rsi_max_call = float(p.get("rsi_max_call", 55.0))
    rsi_min_put = float(p.get("rsi_min_put", 45.0))
    rsi_max_put = float(p.get("rsi_max_put", 75.0))
    wick_min = float(p.get("wick_rejection_ratio", 0.35))
    put_wick_min = float(p.get("put_wick_rejection_ratio", wick_min))
    direction_filter = str(p.get("direction_filter", "BOTH")).upper()
    exclude_weekends = bool(p.get("exclude_weekends", True))

    df_m = df.copy()
    df_m['_orig_idx_'] = df.index
    if df_m['open_time'].max() > 2**32:
        df_m['datetime'] = pd.to_datetime(df_m['open_time'], unit='ms')
    else:
        df_m['datetime'] = pd.to_datetime(df_m['open_time'], unit='s')

    close = df_m['close']
    open_p = df_m['open']
    high = df_m['high']
    low = df_m['low']

    df_m['ema_daily'] = compute_ema(close, ema_daily_p)
    df_m['rsi_daily'] = compute_wilders_rsi(close, rsi_p)
    df_m['rsi_fast'] = compute_wilders_rsi(close, 3)

    df_weekly = _resample_to_weekly(df)
    if not df_weekly.empty:
        df_weekly['ema_weekly'] = compute_ema(df_weekly['close'], ema_weekly_p)
        df_weekly['ema_weekly_dir'] = df_weekly['ema_weekly'].diff()
        is_ms = df_weekly['open_time'].max() > 2**32
        offset = 7 * 24 * 60 * 60 * 1000 if is_ms else 7 * 24 * 60 * 60
        df_weekly['completion_time'] = (df_weekly['open_time'] + offset).astype('int64')
        df_m['open_time'] = df_m['open_time'].astype('int64')

        df_m.sort_values('open_time', inplace=True)
        df_weekly.sort_values('completion_time', inplace=True)

        df_merged = pd.merge_asof(
            df_m,
            df_weekly[['completion_time', 'ema_weekly', 'ema_weekly_dir', 'close']],
            left_on='open_time',
            right_on='completion_time',
            direction='backward',
            suffixes=('', '_weekly')
        )
        df_merged.sort_values('_orig_idx_', inplace=True)
    else:
        df_merged = df_m.copy()
        df_merged['ema_weekly'] = np.nan
        df_merged['ema_weekly_dir'] = np.nan
        df_merged['close_weekly'] = np.nan

    high = df_merged['high']
    low = df_merged['low']
    open_p = df_merged['open']
    close = df_merged['close']
    ema_d = df_merged['ema_daily']
    rsi_d = df_merged['rsi_daily']
    rsi_f = df_merged['rsi_fast']
    ema_w = df_merged['ema_weekly']
    ema_w_dir = df_merged['ema_weekly_dir']
    close_w = df_merged['close_weekly']

    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    atr = tr.rolling(window=14).mean()

    warmup_period = max(14, min(60, len(df_merged) // 3)) if len(df_merged) < 180 else 60
    warmup_mask = np.arange(len(df_merged)) >= warmup_period

    weekly_bull = (close_w > ema_w) & (ema_w_dir > 0)
    weekly_bear = (close_w < ema_w) & (ema_w_dir < 0)

    regime_min_move = float(p.get("regime_min_move", 0.002))
    if regime_min_move > 0:
        ema_prev = ema_w.shift(28)
        regime_move = (ema_w - ema_prev).abs() / ema_prev
        regime_valid = (ema_prev > 0) & (regime_move >= regime_min_move)
        weekly_bull = weekly_bull & regime_valid
        weekly_bear = weekly_bear & regime_valid

    dynamic_tol = np.where((atr.notna()) & (atr > 0) & (close > 0), np.maximum(pullback_tol, (atr / close) * 0.5), pullback_tol)
    pullback_call = (low <= ema_d * (1 + dynamic_tol)) & (close >= ema_d * (1 - dynamic_tol))
    pullback_put = (high >= ema_d * (1 - dynamic_tol)) & (close <= ema_d * (1 + dynamic_tol))

    rsi_call = (rsi_d >= rsi_min_call) & (rsi_d <= rsi_max_call) & (rsi_f <= 50.0)
    rsi_put = (rsi_d >= rsi_min_put) & (rsi_d <= rsi_max_put) & (rsi_f >= 50.0)

    has_vol = ('volume' in df_merged.columns) and (df_merged['volume'].fillna(0).sum() > 0)
    if has_vol:
        vol_sma = df_merged['volume'].rolling(window=20).mean()
        vol_low = (vol_sma == 0) | (df_merged['volume'] < vol_sma)
    else:
        vol_low = pd.Series(True, index=df_merged.index)

    candle_range = high - low
    lower_wick = np.minimum(open_p, close) - low
    upper_wick = high - np.maximum(open_p, close)
    body_ratio = (close - open_p).abs() / np.maximum(candle_range, 1e-8)

    valid_range = candle_range > 0
    wick_rejection_call = np.where(valid_range, (lower_wick / candle_range) >= wick_min, True)
    wick_rejection_put = np.where(valid_range, (upper_wick / candle_range) >= put_wick_min, True)
    body_ok = np.where(valid_range, body_ratio <= 0.45, True)
    dir_close_call = np.where(valid_range, close >= open_p, True)
    dir_close_put = np.where(valid_range, close <= open_p, True)

    open_t = df_merged['open_time']
    is_ms = open_t.max() > 2**32
    sig_timestamps = np.where(is_ms, open_t // 1000, open_t)
    day_of_week = pd.Series(pd.to_datetime(sig_timestamps, unit='s'), index=df_merged.index).dt.weekday

    if exclude_weekends:
        day_valid = day_of_week < 5
    else:
        day_valid = pd.Series(True, index=df_merged.index)

    is_call = warmup_mask & weekly_bull & pullback_call & rsi_call & vol_low & wick_rejection_call & body_ok & dir_close_call & day_valid
    is_put = warmup_mask & weekly_bear & pullback_put & rsi_put & vol_low & wick_rejection_put & body_ok & dir_close_put & day_valid

    if direction_filter == 'CALL':
        is_put = pd.Series(False, index=df_merged.index)
    elif direction_filter == 'PUT':
        is_call = pd.Series(False, index=df_merged.index)

    is_call = is_call & (~is_call.shift(1).fillna(False))
    is_put = is_put & (~is_put.shift(1).fillna(False))

    conflict = is_call & is_put
    is_call = is_call & (~conflict)
    is_put = is_put & (~conflict)

    series_signals = pd.Series(index=df.index, dtype=object)
    call_orig_indices = df_merged.loc[is_call, '_orig_idx_']
    put_orig_indices = df_merged.loc[is_put, '_orig_idx_']

    series_signals.loc[call_orig_indices] = 'CALL'
    series_signals.loc[put_orig_indices] = 'PUT'
    return series_signals

if __name__ == '__main__':
    print("Standalone Python Strategy 'DailyConfluence' initialized.")
'''

        else:
            return f'''# Autogenerated Standalone Python Strategy Script
# Strategy: {strategy_key}
# Created by Antigravity Quant Engine

import pandas as pd
import numpy as np

def compute_wilders_rsi(close: pd.Series, period: int = 14) -> pd.Series:
    closes_val = close.values
    n = len(closes_val)
    rsi_vals = np.full(n, np.nan, dtype=float)
    if n <= period:
        return pd.Series(rsi_vals, index=close.index)
    gains = np.zeros(n)
    losses = np.zeros(n)
    for i in range(1, n):
        diff = closes_val[i] - closes_val[i - 1]
        if diff > 0:
            gains[i] = diff
        else:
            losses[i] = -diff
    avg_gain = np.sum(gains[1:period + 1]) / period
    avg_loss = np.sum(losses[1:period + 1]) / period
    if avg_loss == 0.0:
        rsi_vals[period] = 50.0 if avg_gain == 0.0 else 100.0
    else:
        rs = avg_gain / avg_loss
        rsi_vals[period] = 100.0 - (100.0 / (1.0 + rs))
    for i in range(period + 1, n):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        if avg_loss == 0.0:
            rsi_vals[i] = 50.0 if avg_gain == 0.0 else 100.0
        else:
            rs = avg_gain / avg_loss
            rsi_vals[i] = 100.0 - (100.0 / (1.0 + rs))
    return pd.Series(rsi_vals, index=close.index)

def generate_signals(df: pd.DataFrame, params: dict = {p_repr}) -> pd.Series:
    close = df['close']
    rsi_period = params.get("rsi_period", 14)
    rsi_os = params.get("rsi_oversold", 30.0)
    rsi_ob = params.get("rsi_overbought", 70.0)

    rsi = compute_wilders_rsi(close, rsi_period)
    signals = pd.Series(index=df.index, dtype=object)
    signals.loc[rsi <= rsi_os] = "CALL"
    signals.loc[rsi >= rsi_ob] = "PUT"
    return signals

if __name__ == '__main__':
    print("Standalone Strategy '{strategy_key}' initialized successfully.")
'''

    @staticmethod
    def export_to_pinescript(strategy_key: str, params: dict) -> str:
        """Genera código TradingView PineScript v5 listo para graficar y enviar alertas."""
        strat_key = strategy_key.lower()

        if strat_key == "deesr":
            bb_period = params.get("bb_period", 20)
            bb_std = params.get("bb_std", 2.5)
            kc_period = params.get("kc_period", 20)
            kc_mult = params.get("kc_mult", 2.0)
            rsi_fast = params.get("rsi_fast_period", 3)
            rsi_slow = params.get("rsi_slow_period", 14)
            max_body = params.get("max_body_ratio", 0.45)
            min_wick = params.get("min_wick_ratio", 0.35)

            return f'''//@version=5
indicator("Antigravity Quant Strategy - DEESR", overlay=true)

// Input Parameters
bb_period = input.int({bb_period}, title="Bollinger Period")
bb_std_param = input.float({bb_std}, title="Bollinger Std Dev")
kc_period = input.int({kc_period}, title="Keltner Period")
kc_mult_param = input.float({kc_mult}, title="Keltner Multiplier")
rsi_fast_p = input.int({rsi_fast}, title="RSI Fast Period")
rsi_slow_p = input.int({rsi_slow}, title="RSI Slow Period")
max_body_r = input.float({max_body}, title="Max Body Ratio")
min_wick_r = input.float({min_wick}, title="Min Wick Ratio")

// Indicators Calculation
[bb_middle, bb_upper, bb_lower] = ta.bb(close, bb_period, bb_std_param)
kc_ma = ta.ema(close, kc_period)
kc_atr = ta.atr(kc_period)
kc_upper = kc_ma + (kc_mult_param * kc_atr)
kc_lower = kc_ma - (kc_mult_param * kc_atr)

rsi_fast_val = ta.rsi(close, rsi_fast_p)
rsi_slow_val = ta.rsi(close, rsi_slow_p)

candle_range = high - low
candle_body = math.abs(close - open)
lower_wick = math.min(close, open) - low
upper_wick = high - math.max(close, open)

body_ratio = candle_range > 0 ? (candle_body / candle_range) : 1.0
lower_wick_ratio = candle_range > 0 ? (lower_wick / candle_range) : 0.0
upper_wick_ratio = candle_range > 0 ? (upper_wick / candle_range) : 0.0

// Signal Conditions
bool call_cond = (close <= bb_lower) and (low <= kc_lower) and (rsi_fast_val <= 15.0) and (rsi_slow_val <= 35.0) and (body_ratio <= max_body_r) and (lower_wick_ratio >= min_wick_r)
bool put_cond = (close >= bb_upper) and (high >= kc_upper) and (rsi_fast_val >= 85.0) and (rsi_slow_val >= 65.0) and (body_ratio <= max_body_r) and (upper_wick_ratio >= min_wick_r)

bool call_signal = call_cond and not call_cond[1]
bool put_signal = put_cond and not put_cond[1]

// Visual Plots & Overlay
plot(bb_upper, title="BB Upper", color=color.blue, linewidth=1)
plot(bb_lower, title="BB Lower", color=color.blue, linewidth=1)
plot(kc_upper, title="KC Upper", color=color.purple, linewidth=1)
plot(kc_lower, title="KC Lower", color=color.purple, linewidth=1)

plotshape(call_signal, title="DEESR CALL Signal", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plotshape(put_signal, title="DEESR PUT Signal", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)

alertcondition(call_signal, title="DEESR CALL Alert", message="Binary DEESR CALL Signal Triggered!")
alertcondition(put_signal, title="DEESR PUT Alert", message="Binary DEESR PUT Signal Triggered!")
'''

        elif strat_key in ["islg", "islg_rs"]:
            lookback = params.get("lookback_period", 50)
            sweep_ratio = params.get("min_sweep_atr_ratio", 0.15)
            wick_r = params.get("wick_ratio", 0.35)
            vol_mult = params.get("vol_mult", 1.3)
            rsi_p = params.get("rsi_period", 7)

            return f'''//@version=5
indicator("Antigravity Quant Strategy - ISLG_RS", overlay=true)

// Input Parameters
lookback_p = input.int({lookback}, title="Swing Lookback Period")
sweep_ratio = input.float({sweep_ratio}, title="Min Sweep ATR Ratio")
wick_r = input.float({wick_r}, title="Min Wick Ratio")
vol_mult = input.float({vol_mult}, title="Volume Multiplier")
rsi_p = input.int({rsi_p}, title="RSI Period")

// Indicators Calculation
atr_val = ta.atr(14)
swing_high = ta.highest(high[1], lookback_p)
swing_low = ta.lowest(low[1], lookback_p)

rsi_val = ta.rsi(close, rsi_p)
vol_ma = ta.sma(volume, 20)
vol_spike = na(volume) or vol_ma == 0 or (volume >= vol_ma * vol_mult)

candle_range = high - low
lower_wick = math.min(close, open) - low
upper_wick = high - math.max(close, open)

lower_wick_ratio = candle_range > 0 ? (lower_wick / candle_range) : 0.0
upper_wick_ratio = candle_range > 0 ? (upper_wick / candle_range) : 0.0

// Signal Conditions
bool call_cond = (low < swing_low) and ((swing_low - low) >= (sweep_ratio * atr_val)) and (close >= (swing_low - 0.05 * atr_val)) and (lower_wick_ratio >= wick_r) and vol_spike and (rsi_val <= 30.0)
bool put_cond = (high > swing_high) and ((high - swing_high) >= (sweep_ratio * atr_val)) and (close <= (swing_high + 0.05 * atr_val)) and (upper_wick_ratio >= wick_r) and vol_spike and (rsi_val >= 70.0)

bool call_signal = call_cond and not call_cond[1]
bool put_signal = put_cond and not put_cond[1]

// Visual Plots & Overlay
plot(swing_high, title="Swing High", color=color.red, style=plot.style_stepline)
plot(swing_low, title="Swing Low", color=color.green, style=plot.style_stepline)

plotshape(call_signal, title="ISLG CALL Signal", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plotshape(put_signal, title="ISLG PUT Signal", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)

alertcondition(call_signal, title="ISLG CALL Alert", message="Binary ISLG CALL Signal Triggered!")
alertcondition(put_signal, title="ISLG PUT Alert", message="Binary ISLG PUT Signal Triggered!")
'''

        elif strat_key == "genetic_composite":
            rsi_enabled = "true" if params.get("rsi_enabled", True) else "false"
            rsi_p = params.get("rsi_period", 14)
            rsi_oversold = params.get("rsi_oversold", 30.0)
            rsi_overbought = params.get("rsi_overbought", 70.0)

            bb_enabled = "true" if params.get("bb_enabled", True) else "false"
            bb_period = params.get("bb_period", 20)
            bb_std = params.get("bb_std", 2.0)

            ema_enabled = "true" if params.get("ema_enabled", False) else "false"
            ema_fast_p = params.get("ema_fast_period", 9)
            ema_slow_p = params.get("ema_slow_period", 21)

            pinbar_enabled = "true" if params.get("rejection_filter_enabled", False) else "false"
            pinbar_wick_r = params.get("pinbar_wick_ratio", 0.35)

            sqz_enabled = "true" if params.get("volatility_filter_enabled", False) else "false"
            min_bb_w = params.get("min_bb_width", 0.0)

            htf_ema_enabled = "true" if params.get("htf_ema_enabled", False) else "false"
            htf_ema_p = params.get("htf_ema_period", 100)

            return f'''//@version=5
indicator("Antigravity Quant Strategy - GENETIC_COMPOSITE", overlay=true)

// Input Parameters
rsi_enabled = input.bool({rsi_enabled}, title="RSI Enabled")
rsi_p = input.int({rsi_p}, title="RSI Period")
rsi_oversold = input.float({rsi_oversold}, title="RSI Oversold")
rsi_overbought = input.float({rsi_overbought}, title="RSI Overbought")

bb_enabled = input.bool({bb_enabled}, title="Bollinger Enabled")
bb_period = input.int({bb_period}, title="Bollinger Period")
bb_std_param = input.float({bb_std}, title="Bollinger Std Dev")

ema_enabled = input.bool({ema_enabled}, title="EMA Cross Enabled")
ema_fast_p = input.int({ema_fast_p}, title="EMA Fast Period")
ema_slow_p = input.int({ema_slow_p}, title="EMA Slow Period")

pinbar_enabled = input.bool({pinbar_enabled}, title="Pinbar Filter Enabled")
pinbar_wick_r = input.float({pinbar_wick_r}, title="Pinbar Wick Ratio")

sqz_enabled = input.bool({sqz_enabled}, title="Squeeze Filter Enabled")
min_bb_w = input.float({min_bb_w}, title="Min BB Width")

htf_ema_enabled = input.bool({htf_ema_enabled}, title="HTF EMA Filter Enabled")
htf_ema_p = input.int({htf_ema_p}, title="HTF EMA Period")

// Indicator Calculations
rsi_val = ta.rsi(close, rsi_p)
[bb_mid, bb_upper, bb_lower] = ta.bb(close, bb_period, bb_std_param)
ema_fast = ta.ema(close, ema_fast_p)
ema_slow = ta.ema(close, ema_slow_p)
htf_ema = ta.ema(close, htf_ema_p)

candle_range = high - low
lower_wick = math.min(close, open) - low
upper_wick = high - math.max(close, open)
lower_wick_ratio = candle_range > 0 ? (lower_wick / candle_range) : 0.0
upper_wick_ratio = candle_range > 0 ? (upper_wick / candle_range) : 0.0

// Signal Conditions Assembly
bool call_cond = true
bool put_cond = true

if rsi_enabled
    call_cond := call_cond and (rsi_val <= rsi_oversold)
    put_cond := put_cond and (rsi_val >= rsi_overbought)

if bb_enabled
    call_cond := call_cond and (close[1] >= bb_lower[1] and close < bb_lower)
    put_cond := put_cond and (close[1] <= bb_upper[1] and close > bb_upper)

if ema_enabled
    call_cond := call_cond and (ema_fast > ema_slow)
    put_cond := put_cond and (ema_fast < ema_slow)

if pinbar_enabled
    call_cond := call_cond and (lower_wick_ratio >= pinbar_wick_r)
    put_cond := put_cond and (upper_wick_ratio >= pinbar_wick_r)

if htf_ema_enabled
    call_cond := call_cond and (close > htf_ema)
    put_cond := put_cond and (close < htf_ema)

bool call_signal = call_cond and not call_cond[1]
bool put_signal = put_cond and not put_cond[1]

// Visual Plots & Overlay
plot(bb_upper, title="BB Upper", color=color.blue)
plot(bb_lower, title="BB Lower", color=color.blue)

plotshape(call_signal, title="Genetic CALL Signal", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plotshape(put_signal, title="Genetic PUT Signal", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)

alertcondition(call_signal, title="Genetic CALL Alert", message="Binary Genetic CALL Signal Triggered!")
alertcondition(put_signal, title="Genetic PUT Alert", message="Binary Genetic PUT Signal Triggered!")
'''

        elif strat_key == "daily_confluence":
            ema_w = params.get("ema_weekly_period", 20)
            ema_d = params.get("ema_daily_period", 20)
            rsi_p = params.get("rsi_period", 14)
            pullback_tol = params.get("pullback_tolerance", 0.008)
            rsi_min_call = params.get("rsi_min_call", 25.0)
            rsi_max_call = params.get("rsi_max_call", 55.0)
            rsi_min_put = params.get("rsi_min_put", 45.0)
            rsi_max_put = params.get("rsi_max_put", 75.0)
            wick_min = params.get("wick_rejection_ratio", 0.35)
            dir_filter = params.get("direction_filter", "BOTH")

            return f'''//@version=5
indicator("Antigravity Quant Strategy - DAILY_CONFLUENCE", overlay=true)

// Input Parameters
ema_w_p = input.int({ema_w}, title="EMA Weekly Period")
ema_d_p = input.int({ema_d}, title="EMA Daily Period")
rsi_p = input.int({rsi_p}, title="RSI Period")
pullback_tol = input.float({pullback_tol}, title="Pullback Tolerance")
rsi_min_call = input.float({rsi_min_call}, title="RSI Min CALL")
rsi_max_call = input.float({rsi_max_call}, title="RSI Max CALL")
rsi_min_put = input.float({rsi_min_put}, title="RSI Min PUT")
rsi_max_put = input.float({rsi_max_put}, title="RSI Max PUT")
wick_min = input.float({wick_min}, title="Min Wick Ratio")
dir_filter = input.string("{dir_filter}", title="Direction Filter", options=["BOTH", "CALL", "PUT"])

// Multi-Timeframe Weekly EMA
weekly_close = request.security(syminfo.tickerid, "W", close[1])
weekly_ema = request.security(syminfo.tickerid, "W", ta.ema(close, ema_w_p)[1])
weekly_ema_prev = request.security(syminfo.tickerid, "W", ta.ema(close, ema_w_p)[2])
weekly_ema_dir = weekly_ema - weekly_ema_prev

weekly_bull = (weekly_close > weekly_ema) and (weekly_ema_dir > 0)
weekly_bear = (weekly_close < weekly_ema) and (weekly_ema_dir < 0)

// Daily Indicators Calculation
daily_ema = ta.ema(close, ema_d_p)
daily_rsi = ta.rsi(close, rsi_p)
fast_rsi = ta.rsi(close, 3)
atr_val = ta.atr(14)

dynamic_tol = math.max(pullback_tol, (atr_val / close) * 0.5)
pullback_call = (low <= daily_ema * (1 + dynamic_tol)) and (close >= daily_ema * (1 - dynamic_tol))
pullback_put = (high >= daily_ema * (1 - dynamic_tol)) and (close <= daily_ema * (1 + dynamic_tol))

rsi_call = (daily_rsi >= rsi_min_call) and (daily_rsi <= rsi_max_call) and (fast_rsi <= 50.0)
rsi_put = (daily_rsi >= rsi_min_put) and (daily_rsi <= rsi_max_put) and (fast_rsi >= 50.0)

candle_range = high - low
lower_wick = math.min(close, open) - low
upper_wick = high - math.max(close, open)
body_ratio = candle_range > 0 ? (math.abs(close - open) / candle_range) : 0.0

wick_call = candle_range > 0 ? ((lower_wick / candle_range) >= wick_min) : true
wick_put = candle_range > 0 ? ((upper_wick / candle_range) >= wick_min) : true
body_ok = candle_range > 0 ? (body_ratio <= 0.45) : true

is_weekday = dayofweek != dayofweek.saturday and dayofweek != dayofweek.sunday

bool call_cond = weekly_bull and pullback_call and rsi_call and wick_call and body_ok and (close >= open) and is_weekday
bool put_cond = weekly_bear and pullback_put and rsi_put and wick_put and body_ok and (close <= open) and is_weekday

if dir_filter == "CALL"
    put_cond := false
else if dir_filter == "PUT"
    call_cond := false

bool call_signal = call_cond and not call_cond[1]
bool put_signal = put_cond and not put_cond[1]

// Visual Plots & Overlay
plot(daily_ema, title="Daily EMA 20", color=color.orange, linewidth=2)
plot(weekly_ema, title="Weekly EMA 20", color=color.purple, linewidth=3)

plotshape(call_signal, title="Daily Confluence CALL", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plotshape(put_signal, title="Daily Confluence PUT", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)

alertcondition(call_signal, title="Daily Confluence CALL Alert", message="Binary Daily Confluence CALL Signal Triggered!")
alertcondition(put_signal, title="Daily Confluence PUT Alert", message="Binary Daily Confluence PUT Signal Triggered!")
'''

        else:
            return f'''//@version=5
indicator("Antigravity Quant Strategy - {strategy_key.upper()}", overlay=true)

// Input Parameters
rsi_p = input.int(14, title="RSI Period")
rsi_os = input.float(30.0, title="RSI Oversold")
rsi_ob = input.float(70.0, title="RSI Overbought")

rsi_val = ta.rsi(close, rsi_p)

bool call_signal = rsi_val <= rsi_os and rsi_val[1] > rsi_os
bool put_signal = rsi_val >= rsi_ob and rsi_val[1] < rsi_ob

plotshape(call_signal, title="CALL Signal", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plotshape(put_signal, title="PUT Signal", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)

alertcondition(call_signal, title="CALL Alert", message="Binary CALL Signal Triggered!")
alertcondition(put_signal, title="PUT Alert", message="Binary PUT Signal Triggered!")
'''
